import os
from pathlib import Path
from dotenv import load_dotenv

BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv(BASE_DIR / ".env")

GEMINI_API_KEY = os.getenv("GEMINI_API_KEY", "")
NEWS_API_KEY = os.getenv("NEWS_API_KEY", "")
ALPHA_VANTAGE_KEY = os.getenv("ALPHA_VANTAGE_KEY", "")
TWELVE_DATA_KEY = os.getenv("TWELVE_DATA_KEY", "")
SCAN_INTERVAL = int(os.getenv("SCAN_INTERVAL_MINUTES", "15"))
MAX_STOCKS = int(os.getenv("MAX_STOCKS_PER_SCAN", "40"))
MIN_CONFIDENCE = int(os.getenv("MIN_CONFIDENCE_FOR_SIGNAL", "7"))
PORT = int(os.getenv("PORT", "10000"))

SECTOR_INDICES = {
    "NIFTY AUTO": "^CNXAUTO",
    "NIFTY METAL": "^CNXMETAL",
    "NIFTY IT": "^CNXIT",
    "NIFTY PHARMA": "^CNXPHARMA",
    "NIFTY FMCG": "^CNXFMCG",
    "NIFTY PSU BANK": "^CNXPSUBANK",
    "NIFTY REALTY": "^CNXREALTY",
    "NIFTY INFRA": "^CNXINFRA",
    "NIFTY ENERGY": "^CNXENERGY",
    "NIFTY MEDIA": "^CNXMEDIA",
    "NIFTY50": "^NSEI",
}

SECTOR_STOCKS = {
    "PSU Banks": ["SBIN.NS", "PNB.NS", "BANKBARODA.NS", "CANBK.NS", "IOB.NS", "UCOBANK.NS", "INDIANB.NS", "MAHABANK.NS"],
    "Metal": ["TATASTEEL.NS", "VEDL.NS", "HINDALCO.NS", "JSWSTEEL.NS", "SAIL.NS", "COALINDIA.NS", "NMDC.NS", "JINDALSTEL.NS"],
    "Auto": ["EICHERMOT.NS", "M&M.NS", "MARUTI.NS", "BAJAJ-AUTO.NS", "TVSMOTOR.NS", "HEROMOTOCO.NS", "ASHOKLEY.NS", "HERO.NS"],
    "Capital Markets": ["BSE.NS", "CDSL.NS", "ANGELONE.NS", "MOTILALOFS.NS", "CAMS.NS", "KFINTECH.NS", "MCX.NS", "IEX.NS"],
    "Media": ["SUNTV.NS", "ZEEL.NS", "PVRINOX.NS", "NETWORK18.NS", "TVTODAY.NS"],
    "IT": ["TCS.NS", "INFY.NS", "WIPRO.NS", "HCLTECH.NS", "TECHM.NS", "LTIM.NS", "PERSISTENT.NS", "COFORGE.NS"],
    "Bank": ["HDFCBANK.NS", "ICICIBANK.NS", "KOTAKBANK.NS", "AXISBANK.NS", "INDUSINDBK.NS", "FEDERALBNK.NS"],
    "Pharma": ["SUNPHARMA.NS", "DRREDDY.NS", "CIPLA.NS", "LUPIN.NS", "AUROPHARMA.NS", "DIVISLAB.NS", "BIOCON.NS"],
    "FMCG": ["HINDUNILVR.NS", "ITC.NS", "NESTLEIND.NS", "BRITANNIA.NS", "DABUR.NS", "TATACONSUM.NS", "GODREJCP.NS"],
    "Realty": ["DLF.NS", "GODREJPROP.NS", "OBEROIRLTY.NS", "PRESTIGE.NS", "SOBHA.NS"],
}

HIGH_MOMENTUM_WATCHLIST = [
    "TATASTEEL.NS", "VEDL.NS", "BSE.NS", "CDSL.NS", "ANGELONE.NS",
    "MOTILALOFS.NS", "EICHERMOT.NS", "M&M.NS", "MARUTI.NS",
    "SBIN.NS", "HINDALCO.NS", "JSWSTEEL.NS",
    "COALINDIA.NS", "NMDC.NS", "BEL.NS", "ADANIPORTS.NS",
    "IREDA.NS", "NTPC.NS", "POWERGRID.NS", "LICI.NS",
    "PVRINOX.NS", "SUNTV.NS", "ZEEL.NS", "MCX.NS",
    "IEX.NS", "CAMS.NS", "KFINTECH.NS", "BAJFINANCE.NS",
    "LTIM.NS", "PERSISTENT.NS", "COFORGE.NS",
    "RELIANCE.NS", "HDFCBANK.NS", "INFY.NS", "TCS.NS",
    "BHARTIARTL.NS", "ITC.NS", "KOTAKBANK.NS", "LT.NS",
    "ASIANPAINT.NS", "AXISBANK.NS",
]

SECTOR_NAME_MAP = {
    "NIFTY PSU BANK": "PSU Banks",
    "NIFTY METAL": "Metal",
    "NIFTY AUTO": "Auto",
    "NIFTY MEDIA": "Media",
    "NIFTY IT": "IT",
    "NIFTY PHARMA": "Pharma",
    "NIFTY FMCG": "FMCG",
    "NIFTY REALTY": "Realty",
    "NIFTY INFRA": "Realty",
    "NIFTY ENERGY": "Metal",
    "NIFTY50": "Bank",
}
